public class Main {
    public static void main(String[] args) {
        var dog = 8.0;
        var cat = 3.6;
        var paper = 763789;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        dog = dog+4;
        cat = cat+4;
        paper=paper+4;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        dog = dog-3.5;
        cat = cat-1.6;
        paper=paper-7639;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        var friend = 19;
        System.out.println(friend);
        friend=friend+2;
        System.out.println(friend);
        friend = friend/7;
        System.out.println(friend);
        var frog = 3.5;
        System.out.println(frog);
        frog = frog *10;
        System.out.println(frog);
        frog = frog/3.5;
        System.out.println(frog);
        frog = frog+4;
        System.out.println(frog);
        var massOne=78.2;
        var massTwo=82.7;
        var sum = massOne+massTwo;
        System.out.println(sum);
        var rasn = massTwo-massOne;
        System.out.println(rasn);
        var ost = massOne%massTwo;
        System.out.println(ost);
        var hourGeneral = 640;
        var hourSotr = 8;
        var sotr = hourGeneral/hourSotr;
        System.out.println("Всего работников в компании - "+sotr+" человек");
        sotr = sotr+94;
        var hourSotrNew = hourGeneral/sotr;
        System.out.println("Если в компании работает "+sotr+" человек, то всего "+hourSotrNew+" часа работы можетбыть поделено между сотрудниками");
    }
}